import test from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
const work=process.env.PROJECT_WORKSPACE;
const f=await import(pathToFileURL(join(work,'main.ts')).href);
const ICS='BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nUID:a\nDTSTART:20261014T100000Z\nDTEND:20261014T110000Z\nSUMMARY:Sync\nEND:VEVENT\nEND:VCALENDAR\n';
const WINDOW={start:Date.parse('2026-10-14T09:00:00Z'),end:Date.parse('2026-10-14T17:00:00Z')};
test('reads the authored calendar',()=>assert.equal(f.parseCalendar(ICS).length,1));
test('rejects missing endpoints',()=>assert.throws(()=>f.parseCalendar(ICS.replace('DTEND:20261014T110000Z\n',''))));
test('rejects recurrence',()=>assert.throws(()=>f.parseCalendar(ICS.replace('SUMMARY:Sync','RRULE:FREQ=DAILY\nSUMMARY:Sync')),/recurrence/));
test('rejects timezone guesses',()=>assert.throws(()=>f.parseCalendar(ICS.replace('DTSTART:','DTSTART;TZID=Europe/Paris:')),/timezone/));
test('transparent events do not block',()=>assert.equal(f.parseCalendar(ICS.replace('SUMMARY:Sync','TRANSP:TRANSPARENT\nSUMMARY:Sync')).length,0));
test('unfolds summary text',()=>assert.equal(f.parseCalendar(ICS.replace('SUMMARY:Sync','SUMMARY:One long\n title'))[0].title,'One longtitle'));
test('case-insensitive recurrence cannot bypass rejection',()=>assert.throws(()=>f.parseCalendar(ICS.replace('SUMMARY:Sync','rrule:FREQ=DAILY\nSUMMARY:Sync')),/recurrence/));
test('case-insensitive property names preserve event timing',()=>assert.equal(f.parseCalendar(ICS.replace('DTSTART:','dtstart:'))[0].start,Date.parse('2026-10-14T10:00:00Z')));
test('event outside the envelope is rejected',()=>assert.throws(()=>f.parseCalendar('BEGIN:VCALENDAR\nEND:VCALENDAR\n'+ICS.split('BEGIN:VCALENDAR\nVERSION:2.0\n')[1])));
